---

- name: Get authentication token
  shell: curl -s https://identity.api.rackspacecloud.com/v2.0/tokens -X POST
         -d '{"auth":{"RAX-KSKEY:apiKeyCredentials":{"username":"{{ raxuser }}", "apiKey":"{{ raxkey }}"}}}'
         -H "Content-Type:application/json"
  register: raxauth

- name: Load Balancer discovery request
  rax_clb: name={{ lbname }} port={{ lbport }} protocol={{ lbproto }} algorithm={{ lbalgo }}
           api_key={{ raxkey }} username={{ raxuser }} region={{ raxregion }} wait=yes state=present
  register: raxlb
  
- name: Enable SSL termination and add SSL certificate
  shell: curl -s -X PUT -H "X-Auth-Token:{{ (raxauth.stdout|from_json).access.token.id }}" -H "Content-Type:application/json" -d @"{{ ssljson }}"
         https://{{ raxregion }}.loadbalancers.api.rackspacecloud.com/v1.0/{{ raxid }}/loadbalancers/{{ raxlb.balancer.id }}/ssltermination

- pause: seconds=25

- name: Enable HTTPS redirect on Load Balancer
  shell: curl -s -X PUT -H "X-Auth-Token:{{ (raxauth.stdout|from_json).access.token.id }}" -H "Content-Type:application/json" 
         -d '{"loadBalancer":{"name":"{{ raxlb.balancer.name }}", "protocol":"{{ raxlb.balancer.protocol }}", "httpsRedirect":true}}'
         https://{{ raxregion }}.loadbalancers.api.rackspacecloud.com/v1.0/{{ raxid }}/loadbalancers/{{ raxlb.balancer.id }}